env: development
address:
  internal: 'http://127.0.0.1:8082'
  external: 'http://127.0.0.1:8082'
dirs:
  main: 'C:/NodeJS/oc_client_back/'
  public: 'C:/NodeJS/oc_client_back/public/'
  settings: 'C:/NodeJS/oc_client_back/settings/'
mongoURI: 'mongodb://user:password@ds223019.mlab.com:23019/oc_client_back'
metaServer: 'http://127.0.0.1:8081'
cors: '*'