env: production
address:
  internal: 'http://0.0.0.0:80'
  external: 'https://opencharity.bankex.team'
mongoURI: 'mongodb://opch:testpass@oc_client_mongodb:27017/opch'
cors:
  - 'https://donatorscab.bankex.team'
  - 'https://opencharity.bankex.team'
  - 'https://meta.bankex.team'
token: TOKENPROD