env: staging
address:
  internal: 'http://0.0.0.0:80'
  external: 'https://opencharity.staging.bankex.team'
dirs:
  main: '/oc_client_back/'
  public: '/oc_client_back/public/'
  settings: '/oc_client_back/settings/'
mongoURI: 'mongodb://opch:testpass@oc_client_mongodb:27017/opch'
metaServer: 'https://meta.staging.bankex.team'
cors:
  - 'https://donatorscab.staging.bankex.team'
  - 'https://opencharity.staging.bankex.team'
  - 'https://meta.staging.bankex.team'
  - 'http://127.0.0.1:8080'
  - 'http://127.0.0.1:8081'
  - 'http://127.0.0.1:8082'
  - 'http://127.0.0.1:3000'
