env: staging
address:
  internal: 'http://0.0.0.0:80'
  external: 'https://opencharity.staging.bankex.team'
mongoURI: 'mongodb://opch:testpass@oc_client_mongodb_new:27017/opch'
cors:
  - 'https://donatorscab.staging.bankex.team'
  - 'https://opencharity.staging.bankex.team'
  - 'https://meta.staging.bankex.team'
  - 'http://127.0.0.1:8080'
  - 'http://127.0.0.1:8081'
  - 'http://127.0.0.1:8082'
  - 'http://127.0.0.1:3000'
token: TOKENSTAGE
